apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: nedudipipelinesjavascriptdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nedudipipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: nedudipipelinesjavascriptdocker
    spec:
      containers:
        - name: nedudipipelinesjavascriptdocker
          image: ganttpro.azurecr.io/nedudipipelinesjavascriptdocker
          ports:
          - containerPort: 8080
