apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-basic-instance
  #namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
    #ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /r
          backend:
            serviceName: frontend-service
            servicePort: 80
      #path: /(.*)
      #- backend:
      #    serviceName: hello-world-two
      #    servicePort: 80
      #  path: /hello-world-two(/|$)(.*)
