apiVersion: v1
kind: Service
metadata:
    name: frontend-service
spec:
    type: LoadBalancer
    loadBalancerIP: 20.54.233.86
    ports:
    - port: 80
      targetPort: 8080
    selector:
        app: nedudipipelinesjavascriptdocker