apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  loadBalancerIP: 20.54.137.126
  ports:
  # - port: 8080
  #   targetPort: 80
  #   protocol: TCP
  #   name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nedudipipelinesjavascriptdocker